Assignment3/Activity3/Activity3_Part1/Models/CustomerModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Activity3_Part1.Models
{
    public class CustomerModel
    {

        public int ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }

        public CustomerModel()
        {
            
        }

        public CustomerModel(int id, string name, int age)
        {
            this.ID = id;
            this.Name = name;
            this.Age = age;
        }
    }
}

Assignment3/Activity3/Activity3_Part1/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Activity3_Part1.Models;

namespace Activity3_Part1.Controllers
{
    public class CustomerController : Controller
    {
        public List<CustomerModel> CM = new List<CustomerModel>();
        public CustomerModel customer = new CustomerModel(1, "Zach", 20);
        // GET: Customer
        public ActionResult Index()
        {
            CM.Add(customer);
            var tuple = new Tuple<CustomerModel, List<CustomerModel>>(customer, CM);
              
            return View("CustomerSelect",tuple);
        }

        [HttpPost]
        public ActionResult OnSelectCustomer(string radioCust)
        {
            customer = new CustomerModel(2, radioCust, 1);
            CM.Add(customer);
            var tuple = new Tuple<CustomerModel, List<CustomerModel>>(customer, CM);

            return View("_CustomerDetails", tuple);
        }

        [HttpPost]
        public string GetMoreInfo(string customerID)
        {
          
            return "Hello There";
        }
    }
}

Assignment3/Activity3/Activity3_Part1/Views/Customer/Customer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Customer</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Assignment3/Activity3/Activity3_Part1/Views/Customer/Customer1.cshtml
@model Tuple<Activity3_Part1.Models.CustomerModel, List<Activity3_Part1.Models.CustomerModel>>
@{
    ViewBag.Title = "Customer Selection";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


    <body>
        @Html.Label("Please select a customer");
        @Html.BeginForm("OnSelectCustomer", "Customer", FormMethod.Post, new { id = "myform" }){
        @foreach (var radio in Model.Item2)
        {
            <input type="radio" name="@radio.Name" value="@radio.ID" onchange="myform" />
            @Html.Label(radio.Name);
            <div id="customerinfo">
                @Html.Partial("_CustomerDetails", Model.Item1);
               

            </div>

        }

    </body>

Assignment3/Activity3/Activity3_Part1/Views/Customer/CustomerSelect.cshtml
@model Tuple<Activity3_Part1.Models.CustomerModel, List<Activity3_Part1.Models.CustomerModel>>

@{ 
        ViewBag.Title = "Customer Selection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ new AjaxOptions {HttpMethod = "POST",
      InsertionMode = InsertionMode.Replace,
      UpdateTargetId = "customerInfo"};

    }
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

</head>
<body>
  
    @Html.Label("Please select a customer");
    @Ajax.BeginForm("OnSelectCustomer", "Customer", new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "customerInfo",
    OnSuccess = "ajaxSuccess"
}){
    @foreach (var radio in Model.Item2)
    {
        <input type="radio" name="@radio.Name" value="@radio.ID" onchange="myform" />
        @Html.Label(radio.Name);
<div id="customerinfo">
    @Html.Partial("_CustomerDetails", Model.Item1);
    @Html.Label(radio.Name);
    @Html.Label(radio.Age.ToString());
    <script>$.post('@Url.Action("GetMoreInfo", "Customer")',{ customer: 2},function(DataAnnotationsModelMetadata){ alert(DataAnnotationsModelMetadata); })</script>
</div>

    }
</body>
</html>